### ISSUE TITLE
Sync sessions broken due to min RV version

### ISSUE THREAD

**Issue by chadrik** [AcademySoftwareFoundation/OpenRV#44]
Sync sessions don't currently work because the [minimum RV version is set to "2021.0.2"](https://github.com/AcademySoftwareFoundation/OpenRV/blob/41eccbe03bf2462b399fec6511be1d11de6c6327/src/plugins/rv-packages/sync/sync.mu#L29) and the [default version of OpenRV is "1.0.0"](https://github.com/AcademySoftwareFoundation/OpenRV/blob/41eccbe03bf2462b399fec6511be1d11de6c6327/cmake/globals/rv_version.cmake#L11).  This results in the error "Remote version = 1.0.0, we require 2021.0.2 or above".

One solution to this is to change `minRVVersion` to "1.0.0", but this prevents sync sessions between OpenRV and RV -- RV rejects OpenRV.   We have licenses of RV which we'd like to keep for the added features so we'd like for licensed users to be able to sync with open source users (without requiring them to juggle two different apps).  It would therefore be great if the version of OpenRV matched the version of RV. 

For now I'm setting the version at build time using the cmake defines, but I'm just guessing at the version.

**Comment by rogernelson** [comment]
Good catch.  @bernie-laberge Maybe we should version the sync itself instead of using the RV version? We would need to patch RV versions already out there though.

**Comment by chadrik** [comment]
Has it already been decided that the versioning for OpenRV will differ from RV, or is that still up for debate?

**Comment by rogernelson** [comment]
I don't think it's set it stone.  The version was reset to 1.0 to a) signify a fresh start for OpenRV; and b) releases won't be on a fix schedule tied to the year anymore.

But if it is causing more problems that it solves, it could be worth just putting it back to match the commercial version.  Although, they will eventually become out of sync again, so it might be just kicking the can down the road...

**Comment by compaga** [comment]
We will eventually release a new version of RV that should fix the version miss match for package like Sync. This should allow Sync to work between Open RV and future RV release.

**Comment by bernie-laberge** [comment]
I am closing this. issue as I have just merged this PR which addresses it : https://github.com/AcademySoftwareFoundation/OpenRV/pull/51
Thank you @chadrik !

**Comment by chadrik** [comment]
> We will eventually release a new version of RV that should fix the version miss match for package like Sync. This should allow Sync to work between Open RV and future RV release.

Hi all, as mentioned in this ticket, the problem isn't solved when mixing licensed and "open" clients in a sync session until the licensed RV also gets this fix.  Could you let us know on this ticket when the new version of licensed RV with this fix drops?   Would be greatly appreciated!

**Comment by bernie-laberge** [comment]
Hello Chad, The upcoming RV 2023 contains the fix (the plan is to release it in a matter of weeks).
Now in the mean time, I could send you an invite to the RV Pre-Release program if you wish to test the fix on your end before the release.
Just send me an email to bernard.laberge@autodesk.com if you wish to be added to the RV Pre-Release program.
Thanks

**Comment by chadrik** [comment]
Thanks for the super fast response!  I don't think we'll have the bandwidth for pre-release testing, but we'll be happy to give the new release a test spin when it comes out.
